### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by tooga** [rxdi/firelink#2]
Thanks for the library, it's looking great!

However, there is no license for this library, so we cannot use it in our project. Could you add a license for the project?

**Comment by Stradivario** [comment]
Sure it is MIT license will add it right away :) Hope it works for you since it is created for specific use case. Please let me know if you have any suggestions or comments regarding implementation or  there are missing features. Regards

**Comment by Stradivario** [comment]
@tooga

License added! You can check it here. 

https://github.com/rxdi/firelink/commit/e9d76c566b247caa328e3cd8682116428ee29457

Please if you feel that the issue is resolved click Close :) 

Regards,
Kristiyan Tachev (@Stradivario )

**Comment by tooga** [comment]
Great, thanks!

**Comment by Stradivario** [comment]
Here to help always! @tooga
