### ISSUE TITLE
Error running firelink deploy

### ISSUE THREAD

**Issue by EthanSK** [rxdi/firelink#9]
When I run firelink deploy on my MacOS 10.15.4, I get this:

ssh: Could not resolve hostname file: nodename nor servname provided, or not known
rsync: connection unexpectedly closed (0 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54/rsync/io.c(453) [receiver=2.6.9]

**Comment by Stradivario** [comment]
I see some SSH output maybe this is what is causing it ? 

I think rsync implementations in linux and mac are different thus i will need to create native nodejs implementation in order to get it  working. Please specify some more details.

Are you connecting somehow using SSH  and remote server ?

**Comment by Stradivario** [comment]
Will close due to inactivity from the author.

Moving discussion to the feature topic

https://github.com/rxdi/firelink/issues/11


Please feel free to re-open if neeeded.

Regards,
Kristiyan Tachev

**Comment by Stradivario** [comment]
@EthanSK 

RSync is removed from the library now it is using native nodejs `file system` API's 

https://github.com/rxdi/firelink/pull/23

Cheers!
